services:
  # Main Services for base dev-hub
  hub:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - mysql
      - mongo
    networks:
      - dev-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p root_password",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: dbadmin
      PMA_PASSWORD: dbadmin_password
      PMA_ARBITRARY: 1
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dev-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - dev-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
    networks:
      - dev-network

  # Project mounts
  taskmaster:
      build: ./skill-showcases/taskmaster/app
      ports:
        - "3002:3002"
      depends_on:
        - mongo
      volumes:
        - ./skill-showcases/taskmaster/app:/app
      environment:
        - MONGO_URI=mongodb://mongo:27017/taskmaster
      networks:
        - dev-network

# Volumes and Network
volumes:
  mysql-data:
  mongo-data:

networks:
  dev-network:
    driver: bridge
